admins:
  - username: admin
    password_hash: "$2b$10$ZW4Jy7ctIt7k9V1AogFky.v4wedLF92t4/ZlT9kWPlIiCmdQNzJ.C" # password: adminpass
    discord_id: "1234567890"
    lockdown: false
  - username: lockdown
    password_hash: "$2b$10$n0L0oe1ZQy7IgM.FvVAzb.aXz43uaZWFiT0wr.05uNoVIDLawmrCG" # password: lockdownpass
    discord_id: "0987654321"
    lockdown: true
media:
  # Base URL for mediaMTX WHEP publishes. Append the rover ID automatically, or embed {roverId}/{id}.
  # Examples:
  #   http://192.168.0.86:8889/whep          -> becomes http://192.168.0.86:8889/whep/<roverId>
  #   http://192.168.0.86:8889/{id}/whep     -> becomes http://192.168.0.86:8889/Freaky/whep
  whepBaseUrl: "http://192.168.0.86:8889/whep"
